### PR TITLE
Add `WebExtension` support

### PR DESCRIPTION
**Pull request by jamietanna**
In order to support newer versions of Firefox, we need to use a `WebExtension`.

### CODE REVIEW

**Comment by jamietanna** [comment]
Questions:

- [x] Did you want me to delete the legacy Firefox extension that doesn't work?
- [ ] This currently uses hardcoded configuration variables like `localhost:9000`. Did you want this to be configurable via an options page?

**Comment by agiz** [comment]
First of all thank you for the PR :). Yes, there is probably no reason to keep legacy Firefox extension. Configuration via an options page would be nice.

Do you want me to merge this PR and then sort above issues in a new one or should I want for an update?

**Comment by jamietanna** [comment]
@agiz always happy to help with this project! I'll get it sorted within this PR - I'll send through the changes next week :)

**Comment by piousminion** [comment]
@jamietanna I have your changes, but I am lost as to what to do with them. Not that I had any clue what to do with the old firefox extension. lol    Any tips?

**Comment by jamietanna** [comment]
@piousminion something I didn't mention is that we'd want to get the WebExtension published. Until then, you can navigate to `about:debugging#addons` and `Load Temporary Add-on`, then navigate to `package.json` and select it. That will give you the extension until your next restart of Firefox.

**Comment by jamietanna** [comment]
Hey @agiz, I didn't get the chance to do the options page. Should I create an issue for this? Or is it worth reverting the merge until I can add it?

**Comment by agiz** [comment]
Hey. Mea culpa. Umm, I guess it's easier to just create new issue.

**Pull request merged**
